//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADAuthenticationService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ZainEmployee", Namespace="http://tempuri.org/")]
    public partial class ZainEmployee : object
    {
        
        private string userIDField;
        
        private string NameField;
        
        private string MobileNumberField;
        
        private string emailField;
        
        private bool isAuthintecatedField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string userID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string Name
        {
            get
            {
                return this.NameField;
            }
            set
            {
                this.NameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MobileNumber
        {
            get
            {
                return this.MobileNumberField;
            }
            set
            {
                this.MobileNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public bool isAuthintecated
        {
            get
            {
                return this.isAuthintecatedField;
            }
            set
            {
                this.isAuthintecatedField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ADAuthenticationService.ADAuthenticationServiceSoap")]
    public interface ADAuthenticationServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAuthenticated", ReplyAction="*")]
        System.Threading.Tasks.Task<ADAuthenticationService.IsAuthenticatedResponse> IsAuthenticatedAsync(ADAuthenticationService.IsAuthenticatedRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IsAuthenticatedMada", ReplyAction="*")]
        System.Threading.Tasks.Task<ADAuthenticationService.IsAuthenticatedMadaResponse> IsAuthenticatedMadaAsync(ADAuthenticationService.IsAuthenticatedMadaRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticated", Namespace="http://tempuri.org/", Order=0)]
        public ADAuthenticationService.IsAuthenticatedRequestBody Body;
        
        public IsAuthenticatedRequest()
        {
        }
        
        public IsAuthenticatedRequest(ADAuthenticationService.IsAuthenticatedRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string domainName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string path;
        
        public IsAuthenticatedRequestBody()
        {
        }
        
        public IsAuthenticatedRequestBody(string domainName, string userName, string password, string path)
        {
            this.domainName = domainName;
            this.userName = userName;
            this.password = password;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticatedResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADAuthenticationService.IsAuthenticatedResponseBody Body;
        
        public IsAuthenticatedResponse()
        {
        }
        
        public IsAuthenticatedResponse(ADAuthenticationService.IsAuthenticatedResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ADAuthenticationService.ZainEmployee IsAuthenticatedResult;
        
        public IsAuthenticatedResponseBody()
        {
        }
        
        public IsAuthenticatedResponseBody(ADAuthenticationService.ZainEmployee IsAuthenticatedResult)
        {
            this.IsAuthenticatedResult = IsAuthenticatedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedMadaRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticatedMada", Namespace="http://tempuri.org/", Order=0)]
        public ADAuthenticationService.IsAuthenticatedMadaRequestBody Body;
        
        public IsAuthenticatedMadaRequest()
        {
        }
        
        public IsAuthenticatedMadaRequest(ADAuthenticationService.IsAuthenticatedMadaRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedMadaRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string domainName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string userName;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string password;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string path;
        
        public IsAuthenticatedMadaRequestBody()
        {
        }
        
        public IsAuthenticatedMadaRequestBody(string domainName, string userName, string password, string path)
        {
            this.domainName = domainName;
            this.userName = userName;
            this.password = password;
            this.path = path;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class IsAuthenticatedMadaResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="IsAuthenticatedMadaResponse", Namespace="http://tempuri.org/", Order=0)]
        public ADAuthenticationService.IsAuthenticatedMadaResponseBody Body;
        
        public IsAuthenticatedMadaResponse()
        {
        }
        
        public IsAuthenticatedMadaResponse(ADAuthenticationService.IsAuthenticatedMadaResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class IsAuthenticatedMadaResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ADAuthenticationService.ZainEmployee IsAuthenticatedMadaResult;
        
        public IsAuthenticatedMadaResponseBody()
        {
        }
        
        public IsAuthenticatedMadaResponseBody(ADAuthenticationService.ZainEmployee IsAuthenticatedMadaResult)
        {
            this.IsAuthenticatedMadaResult = IsAuthenticatedMadaResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public interface ADAuthenticationServiceSoapChannel : ADAuthenticationService.ADAuthenticationServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.2.0-preview1.23462.5")]
    public partial class ADAuthenticationServiceSoapClient : System.ServiceModel.ClientBase<ADAuthenticationService.ADAuthenticationServiceSoap>, ADAuthenticationService.ADAuthenticationServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ADAuthenticationServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(ADAuthenticationServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), ADAuthenticationServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADAuthenticationServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ADAuthenticationServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADAuthenticationServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ADAuthenticationServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ADAuthenticationServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ADAuthenticationService.IsAuthenticatedResponse> ADAuthenticationService.ADAuthenticationServiceSoap.IsAuthenticatedAsync(ADAuthenticationService.IsAuthenticatedRequest request)
        {
            return base.Channel.IsAuthenticatedAsync(request);
        }
        
        public System.Threading.Tasks.Task<ADAuthenticationService.IsAuthenticatedResponse> IsAuthenticatedAsync(string domainName, string userName, string password, string path)
        {
            ADAuthenticationService.IsAuthenticatedRequest inValue = new ADAuthenticationService.IsAuthenticatedRequest();
            inValue.Body = new ADAuthenticationService.IsAuthenticatedRequestBody();
            inValue.Body.domainName = domainName;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.path = path;
            return ((ADAuthenticationService.ADAuthenticationServiceSoap)(this)).IsAuthenticatedAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ADAuthenticationService.IsAuthenticatedMadaResponse> ADAuthenticationService.ADAuthenticationServiceSoap.IsAuthenticatedMadaAsync(ADAuthenticationService.IsAuthenticatedMadaRequest request)
        {
            return base.Channel.IsAuthenticatedMadaAsync(request);
        }
        
        public System.Threading.Tasks.Task<ADAuthenticationService.IsAuthenticatedMadaResponse> IsAuthenticatedMadaAsync(string domainName, string userName, string password, string path)
        {
            ADAuthenticationService.IsAuthenticatedMadaRequest inValue = new ADAuthenticationService.IsAuthenticatedMadaRequest();
            inValue.Body = new ADAuthenticationService.IsAuthenticatedMadaRequestBody();
            inValue.Body.domainName = domainName;
            inValue.Body.userName = userName;
            inValue.Body.password = password;
            inValue.Body.path = path;
            return ((ADAuthenticationService.ADAuthenticationServiceSoap)(this)).IsAuthenticatedMadaAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ADAuthenticationServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.ADAuthenticationServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpTransportBindingElement httpBindingElement = new System.ServiceModel.Channels.HttpTransportBindingElement();
                httpBindingElement.AllowCookies = true;
                httpBindingElement.MaxBufferSize = int.MaxValue;
                httpBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.ADAuthenticationServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.210.12/ADAuthentication/ADAuthenticationService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.ADAuthenticationServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.210.12/ADAuthentication/ADAuthenticationService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            ADAuthenticationServiceSoap,
            
            ADAuthenticationServiceSoap12,
        }
    }
}
